#!/bin/bash

if [ ! -e "veles/znicz/.project" -o ! -e libSoundFeatureExtraction/.project ]; then
	user=$(git remote -v | grep -oE '//[^@]+' -m1 | cut -c3-)
    sed -i "/$user/b; s/ssh:\/\//ssh:\/\/$user@/g" .gitmodules
    git submodule update --init
    git checkout .gitmodules
    echo '[filter "package"]
        clean = /bin/sh package.sh clean
        smudge = /bin/sh package.sh smudge' >> .git/config
    echo '[filter "package"]
        clean = /bin/sh package.sh clean
        smudge = /bin/sh package.sh smudge' >> .git/modules/Znicz/config
    rm veles/__init__.py
    git checkout veles/__init__.py
    rm veles/znicz/__init__.py
    git checkout veles/znicz/__init__.py
else
    git submodule update
fi
