# -*- coding: utf-8 -*-
'''
Created on May 21, 2013

Copyright (c) 2013 Samsung Electronics Co., Ltd.
'''


from email.utils import parsedate_tz, mktime_tz
from sys import version_info
from warnings import warn


__project__ = "Veles Machine Learning Platform"
__version__ = "0.3.0"
__license__ = "Samsung Proprietary License"
__copyright__ = "© 2013 Samsung Electronics Co., Ltd."
__authors__ = ["Gennady Kuznetsov", "Vadim Markovtsev", "Alexey Kazantsev",
               "Lyubov Podoynitsina", "Denis Seresov", "Dmitry Senin",
               "Alexey Golovizin", "Egor Bulychev", "Ernesto Sanches"]

try:
    __git__ = "$Commit$"
    __date__ = mktime_tz(parsedate_tz("$Date$"))
except Exception as ex:
    warn("Cannot expand variables generated by Git, setting them to None")
    __git__ = None
    __date__ = None

if version_info.major == 3 and version_info.minor == 4 and \
   version_info.micro < 1:
    warn("Python 3.4.0 has a bug which is critical to Veles OpenCL subsystem ("
         "see issue #21435). It is recommended to upgrade to 3.4.1.")

from veles.logger import Logger
from veles.units import Unit
from veles.opencl_units import OpenCLUnit, OpenCLWorkflow
from veles.workflow import Workflow
